version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  giga-ub:
    image: giga-ub
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
