version: '3.9'
services:
  db:
    image: redis:latest
    restart: always
    networks:
      - gigaub
    volumes:
      - giga-db-data:/data
  giga-ub:
    image: giga-ub
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - gigaub

volumes:
  giga-db-data:

networks:
  gigaub:
